### ISSUE TITLE
OSX build failed

### ISSUE THREAD

**Issue by kktam** [vshatskyi/black-screen#921]
OSX compiled has failed and just sending the error stack to see if I can get some information on how to build it succesfully.

OSX Yosemite 10.10.5
npm 3.10.8
node v6.9.1
electron 1.4.8

```
> black-screen@0.2.97 electron /Users/n/Documents/Work/nodejs/black-screen
> electron .

fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/n/Documents/Work/nodejs/black-screen/node_modules/electron-prebuilt/path.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.<anonymous> (/Users/n/Documents/Work/nodejs/black-screen/node_modules/electron-prebuilt/index.js:4:42)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/Users/n/Documents/Work/nodejs/black-screen/node_modules/.bin/npm" "run" "electron"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! black-screen@0.2.97 electron: `electron .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the black-screen@0.2.97 electron script 'electron .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the black-screen package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs black-screen
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls black-screen
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/n/Documents/Work/nodejs/black-screen/npm-debug.log
```

**Comment by drew-gross** [comment]
Looks like a missing file error. Maybe it got deleted, or failed to download properly.
